### PR TITLE
HAWKULAR-877 - Enabled the Secret Store

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling see the inline comments. Except for that, could you please change the date of the commit to 2016 not to mess with the license plugin?

**Comment by ppalaga** [comment]
@jpkrohling could you please explain what is the relevance of this PR for Command Gateway? Does it make any sense to add `secret-store-undertow-filter` even though cmdgw does not expose any HTTP endpoints?

**Comment by jpkrohling** [comment]
I changed based on the comments. Also, I changed the listener to use the one from the secret store, as that's the right one for this purpose. 

About the inclusion of the secret store itself: as I understand, there's authentication of socket messages. On this part, the authentication can be done with OAuth tokens, username/password or key/secret. For the key/secret part, the secret store is needed.

**Comment by ppalaga** [comment]
@jpkrohling the tests are very new here. I am not sure if the CI fail is a true or false fail. The test are maybe executed too early? - e.g. they need to wait for accounts to initialize?

**Comment by jpkrohling** [comment]
To be honest, I had a Hawkular instance running locally and didn't run the full suite here. Let me test it and I'll post the results here.

**Comment by jpkrohling** [comment]
I ran the tests here and updated the code. Note that I added a dependency to secret-store-api that would not be necessary, but I was having issues with it locally, as it seems that it's pom.xml is currently in some blackhole for "some" repos. 

Anyway, it should now pass.

**Comment by jpkrohling** [comment]
New parent, not managing undertow-filter here anymore.

**Pull request merged**
